// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApesE5BCdUpglMpddGltiFKKY9fYMrfxA',
    appId: '1:524142426102:android:b09ec58f4bc663c3c639d7',
    messagingSenderId: '524142426102',
    projectId: 'mylibrary-app-4f780',
    storageBucket: 'mylibrary-app-4f780.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKK9Uiglmv9Bu5HKh0jghQJhSLQ2YtXqY',
    appId: '1:524142426102:ios:ad07364b202a6707c639d7',
    messagingSenderId: '524142426102',
    projectId: 'mylibrary-app-4f780',
    storageBucket: 'mylibrary-app-4f780.appspot.com',
    androidClientId: '524142426102-ltif2jvvir00nthd982e34ffdqll4j9f.apps.googleusercontent.com',
    iosClientId: '524142426102-c4s8i8gs4ak6tigtmubfmune2op1ub5g.apps.googleusercontent.com',
    iosBundleId: 'com.dogukanozgurylmz.mylib.mylibApp',
  );
}
